### PR TITLE
Remove C-ext dpendency

### PR DESCRIPTION
**Pull request by ko1**
I rewrite pure-ruby version.
Could you apply it?
Or should I fork project?

Thanks,
Koichi

### CODE REVIEW

**Comment by ko1** [comment]
It may be fine for 1.9.3, 2.0.0 and trunk.

**Comment by cldwalker** [comment]
Koichi, thanks for the pull. Is the rewrite to better support 2.0.0? Does this support 1.9.2? I'm trying to have debugger support 1.9.2 but I may consider dropping it for 2.0.x support

**Comment by ko1** [comment]
> Is the rewrite to better support 2.0.0? 

I want to remove dependency to ruby_core_source.
Now, I already remove dependency to ruby_core_source in debugger gem (I'm debugging now :)).

> Does this support 1.9.2? 

Maybe yes. Sorry I don't check it.

**Comment by cldwalker** [comment]
Removing dependency on debugger-ruby_core_source would be great :) debugger has more header dependencies [here](https://github.com/cldwalker/debugger/blob/master/ext/ruby_debug/extconf.rb)

**Comment by ko1** [comment]
On my laptop, I already remove dependency from debugger  (only for Ruby 2.0).
I'll fork debugger for Ruby 2.0.

Anyway, do you have any problem to accept my pull request?

**Comment by cldwalker** [comment]
Tests pass on 1.9.x and 2.0. Thanks!

**Comment by ko1** [comment]
Thanks!!

Any gem update scheduled?

**Comment by cldwalker** [comment]
I've pushed 1.2.0 of this gem. I'll update debugger when I push the next minor version

**Pull request merged**
